services:
  - type: web
    name: bukber-babel2026
    env: php
    plan: free
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader && npm ci && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
